# Generated by Django 5.1.15 on 2026-09-09 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSED', 'Processed'), ('APPROVED', 'Approved'), ('NEEDS_REVIEW', 'Needs Review'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=20)),
                ('missed_doses_past_week', models.PositiveIntegerField(default=0, help_text='Number of missed doses reported over the previous 7 days (>= 0)')),
                ('has_severe_symptoms', models.BooleanField(default=False, help_text='Whether patient experiences severe or acute symptoms')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='patients.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_requests', to='patients.patientprescription')),
            ],
            options={
                'db_table': 'refill_requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('BLOOD_PRESSURE', 'Blood Pressure Monitor'), ('GLUCOMETER', 'Glucometer')], max_length=20)),
                ('image_storage_uri', models.TextField(help_text='Compliant sovereign object storage URI path')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('refill_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='refills.refillrequest')),
            ],
            options={
                'db_table': 'device_scans',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='refillrequest',
            index=models.Index(fields=['patient', 'status'], name='idx_refill_patient_status'),
        ),
        migrations.AddIndex(
            model_name='refillrequest',
            index=models.Index(fields=['prescription', '-submitted_at'], name='idx_refill_rx_timeline'),
        ),
        migrations.AddConstraint(
            model_name='refillrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'PROCESSED', 'APPROVED', 'NEEDS_REVIEW', 'REJECTED'])), name='chk_refill_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='refillrequest',
            constraint=models.CheckConstraint(condition=models.Q(('missed_doses_past_week__gte', 0)), name='chk_refill_missed_doses_non_negative'),
        ),
        migrations.AddIndex(
            model_name='devicescan',
            index=models.Index(fields=['refill_request', 'device_type'], name='idx_scan_req_device'),
        ),
        migrations.AddConstraint(
            model_name='devicescan',
            constraint=models.CheckConstraint(condition=models.Q(('device_type__in', ['BLOOD_PRESSURE', 'GLUCOMETER'])), name='chk_device_type_valid'),
        ),
    ]
