# Generated by Django 5.1.15 on 2026-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_chk_patient_glucose_positive_and_more'),
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicescan',
            name='refill_request',
        ),
        migrations.AddConstraint(
            model_name='refillrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'NEEDS_REVIEW', 'PROCESSED'])), fields=('prescription',), name='uq_refill_prescription_pending'),
        ),
        migrations.DeleteModel(
            name='DeviceScan',
        ),
    ]
