# Generated by Django 5.1.15 on 2026-09-09 10:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=4, help_text='OCR model extraction confidence score [0.0000, 1.0000]', max_digits=5)),
                ('systolic', models.IntegerField(blank=True, help_text='Extracted systolic blood pressure in mmHg', null=True)),
                ('diastolic', models.IntegerField(blank=True, help_text='Extracted diastolic blood pressure in mmHg', null=True)),
                ('glucose', models.DecimalField(blank=True, decimal_places=2, help_text='Extracted blood glucose in mg/dL', max_digits=5, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Raw OCR model outputs and coordinate metadata')),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('refill_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='refills.refillrequest')),
            ],
            options={
                'db_table': 'ocr_results',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['refill_request', '-processed_at'], name='idx_ocr_refill_processed')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence_score__gte', Decimal('0.0000')), ('confidence_score__lte', Decimal('1.0000'))), name='chk_ocr_confidence_score_range')],
            },
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('triage_color', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10)),
                ('anomaly_reason', models.CharField(blank=True, choices=[('PHYSIOLOGICAL_IMPOSSIBILITY', 'Physiological Impossibility'), ('SUSPECTED_DATA_FABRICATION', 'Suspected Data Fabrication'), ('LOW_OCR_CONFIDENCE', 'Low OCR Confidence'), ('CLINICAL_VARIANCE_EXCEEDED', 'Clinical Variance Exceeded'), ('SEVERE_SYMPTOMS_REPORTED', 'Severe Symptoms Reported')], max_length=100, null=True)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refill_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_record', to='refills.refillrequest')),
            ],
            options={
                'db_table': 'triage_records',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('triage_color__in', ['GREEN', 'YELLOW', 'RED'])), name='chk_triage_color_valid')],
            },
        ),
    ]
