# Generated by Django 5.1.15 on 2026-09-10 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0002_remove_devicescan_refill_request_and_more'),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagerecord',
            name='anomaly_reason',
            field=models.CharField(blank=True, choices=[('PHYSIOLOGICAL_IMPOSSIBILITY', 'Physiological Impossibility'), ('SUSPECTED_DATA_FABRICATION', 'Suspected Data Fabrication'), ('CLINICAL_VARIANCE_EXCEEDED', 'Clinical Variance Exceeded'), ('SEVERE_SYMPTOMS_REPORTED', 'Severe Symptoms Reported')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='IntakeTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('systolic', models.IntegerField(blank=True, help_text='Extracted systolic blood pressure in mmHg', null=True)),
                ('diastolic', models.IntegerField(blank=True, help_text='Extracted diastolic blood pressure in mmHg', null=True)),
                ('glucose', models.DecimalField(blank=True, decimal_places=2, help_text='Extracted blood glucose in mg/dL', max_digits=5, null=True)),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('refill_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='refills.refillrequest')),
            ],
            options={
                'db_table': 'intake_telemetry',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OCRResult',
        ),
        migrations.AddIndex(
            model_name='intaketelemetry',
            index=models.Index(fields=['refill_request', '-processed_at'], name='idx_telemetry_refill_processed'),
        ),
    ]
