# Generated by Django 5.1.15 on 2026-09-09 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('voucher_code', models.CharField(db_index=True, help_text='Cryptographically strong, non-sequential 16-character alphanumeric code', max_length=16, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPENSED', 'Dispensed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Expiration timestamp (96 hours after issuance)')),
                ('dispensed_at', models.DateTimeField(blank=True, help_text='Timestamp when medication was dispensed at pharmacy POS', null=True)),
                ('dispensing_pharmacy_id', models.CharField(blank=True, help_text='Unique identifier of the dispensing pharmacy branch', max_length=100, null=True)),
                ('refill_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='refills.refillrequest')),
            ],
            options={
                'db_table': 'pharmacy_vouchers',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'DISPENSED', 'EXPIRED', 'CANCELLED'])), name='chk_voucher_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('dispensed_at__isnull', False), ('dispensing_pharmacy_id__isnull', False), ('status', 'DISPENSED')), models.Q(('status', 'DISPENSED'), _negated=True), _connector='OR'), name='chk_voucher_dispensed_fields')],
            },
        ),
    ]
