# Generated by Django 5.1.15 on 2026-09-09 09:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('national_id', models.CharField(db_index=True, max_length=14, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=32)),
                ('baseline_systolic', models.PositiveSmallIntegerField(help_text='Baseline systolic blood pressure in mmHg (50 - 300)')),
                ('baseline_diastolic', models.PositiveSmallIntegerField(help_text='Baseline diastolic blood pressure in mmHg (30 - 200)')),
                ('baseline_glucose', models.DecimalField(blank=True, decimal_places=2, help_text='Baseline blood glucose concentration in mg/dL (> 0)', max_digits=5, null=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='idx_patient_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('baseline_systolic__gte', 50), ('baseline_systolic__lte', 300)), name='chk_patient_systolic_range'), models.CheckConstraint(condition=models.Q(('baseline_diastolic__gte', 30), ('baseline_diastolic__lte', 200)), name='chk_patient_diastolic_range'), models.CheckConstraint(condition=models.Q(('baseline_systolic__gt', models.F('baseline_diastolic'))), name='chk_patient_systolic_greater_than_diastolic'), models.CheckConstraint(condition=models.Q(('baseline_glucose__isnull', True), ('baseline_glucose__gt', 0), _connector='OR'), name='chk_patient_glucose_positive')],
            },
        ),
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('refill_interval_days', models.PositiveIntegerField(default=30, help_text='Refill cycle interval in days (> 0)')),
                ('last_dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_prescriptions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['patient', 'is_active'], name='idx_rx_patient_active'), models.Index(fields=['medication_name'], name='idx_rx_medication_name')],
                'constraints': [models.CheckConstraint(condition=models.Q(('refill_interval_days__gt', 0)), name='chk_prescription_refill_interval_positive'), models.UniqueConstraint(django.db.models.functions.text.Lower('medication_name'), models.F('patient'), condition=models.Q(('is_active', True), ('is_deleted', False)), name='uq_patient_active_medication')],
            },
        ),
    ]
