# Generated by Django 5.1.15 on 2026-09-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='chk_patient_glucose_positive',
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('baseline_glucose__isnull', True), models.Q(('baseline_glucose__gt', 0), ('baseline_glucose__lte', 1000)), _connector='OR'), name='chk_patient_glucose_positive'),
        ),
    ]
