# Generated by Django 5.1.15 on 2026-09-09 11:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAdjudication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_user_id', models.UUIDField(db_index=True, help_text='UUID identifying the licensed adjudicating clinician')),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('rejection_reason_category', models.CharField(blank=True, choices=[('UNVERIFIABLE_DEVICE_IMAGE', 'Unverifiable Device Image'), ('SUSPECTED_FRAUD_TAMPERING', 'Suspected Fraud / Data Tampering'), ('PHYSIOLOGICAL_DANGER', 'Acute Physiological Danger'), ('CLINICAL_CONTRAINDICATION', 'Clinical Contraindication'), ('EXCESSIVE_DOSAGE_VARIANCE', 'Excessive Biometric Variance'), ('OTHER', 'Other Clinical Rationale')], max_length=100, null=True)),
                ('clinical_notes', models.TextField(help_text='Mandatory substantive clinical justification and clearance rationale')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refill_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_adjudication', to='refills.refillrequest')),
            ],
            options={
                'db_table': 'manual_adjudications',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('decision__in', ['APPROVE', 'REJECT'])), name='chk_adjudication_decision_valid'), models.CheckConstraint(condition=models.Q(('decision', 'APPROVE'), models.Q(('decision', 'REJECT'), ('rejection_reason_category__isnull', False), models.Q(('rejection_reason_category', ''), _negated=True), models.Q(('clinical_notes', ''), _negated=True)), _connector='OR'), name='chk_adjudication_rejection_conditional')],
            },
        ),
    ]
